Allow manually setting step `cssPosition` to `fixed`
nutshellcrm/react-joyride pull request #8
Opened 2016-12-14 20:45 UTC by chriscain

In the current implementation, the step would just check its selector's target, and then calculate the `cssPosition` from that target's position. However, if the container of that selector was fixed, this wouldn't work. Furthermore, the `joyride-hole` property was always set to `position: absolute`, which needs to be dynamically set instead.

**Changes**
- Removed hardcoded `position: absolute` from `.joyride-hole`
- Still uses the target’s css position as a fallback, but if any value
is passed from cssPosition, that value overrides everything else
- Changes calculations for calcPlacement’s y value, as the body.top
property must be ignore /w fixed position
- Pass in calculated cssPosition to Tooltip component

2016-12-14 21:22 UTC, IanVS requested changes
This LGTM, but would you mind updating the readme to add the `isFixedPosition` property to the step definition?

2016-12-14 21:22 UTC, IanVS commented on src/styles/react-joyride.css
> -  position: absolute;
One annoying thing about what I did in duplicating the styles in this project is that we need to change this in two places.  Here, and in https://github.com/nutshellcrm/react-joyride/blob/4a534e6fb618565ab83512faa6f7071ff68e035e/src/styles/react-joyride.scss#L115

2016-12-19 19:36 UTC, chriscain commented on src/styles/react-joyride.css
> -  position: absolute;
removed, thanks

2016-12-19 22:10 UTC, IanVS approved these changes

2016-12-19 22:10 UTC, merged